### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by erokoder** [seikan/homebridge-sonoff-basic-espeasy#2]
When power on lights delay is about 7 seconds. But when turn off, no delay.  Could this be fixed?

**Comment by pbksol** [comment]
That's not related to the plugin but the ESPEasy Firmware Version you are using. Flash the device to the latest 2.0.0 Dev "Normal" and everything will become lightning fast.

**Comment by erokoder** [comment]
Thats right, after update firmware to 2.0.0dev12normal, all lights fast turn on and off.
Thanks for information.
