### ISSUE TITLE
Option for ServiceType

### ISSUE THREAD

**Issue by migabc** [seikan/homebridge-sonoff-basic-espeasy#4]
Can you put in an option for the ServiceType:
Where ServiceType can be one of the following:

Switch
Lightbulb
Outlet

Example:
    {
      "accessory": "SonoffBasicESPEasy",
      "name": "Living Room Switch",
      "ServiceType": Outlet,
      "ip": "IP_ADDRESS_OF_THE_SONOFF_BASIC"
    }

**Comment by erokoder** [comment]
You can always hardcode some thing.
In your case, if you want Lightbulb change code in index.js :
`19. 	this.service = new Service.Switch(this.name);`
**with**
`19.   this.service = new Service.Lightbulb(this.name);`
or
`19.   this.service =new Service.Outlet(this.name)`

If you want in same time use Lightbulb and Switch, tell me.
I will send update code, and you only must paste in index.js

**Comment by seikan** [comment]
Outlet support  added. To use as light/lightbulb,  you can change the type in your Homekit app.

**Comment by migabc** [comment]
I already had included Outlets and Lightbulbs
Thanks for publishing the new version.
